### ISSUE TITLE
Leaflet is blank unless `incl.data = TRUE`

### ISSUE THREAD

**Issue by ntdef** [chgrl/leafletR#10]
I'm having trouble displaying leaflet maps: I copy-paste'd the example code and the leaflet came up completely blank. I went back and set `leaflet(data=data, incl.data=TRUE)`, and everything worked great. However, I would still like to be able to keep the data separate from the `map.html`. Anyway to fix this behavior?

P.S. Great package: really easy to use :+1:

**Comment by juliohm** [comment]
This information about Chrome should be included in the manual!

**Comment by chgrl** [comment]
The information is included:

> incl.data
> If TRUE, data is included in the HTML file itself. Per default (incl.data=FALSE) the data is saved in a separate file. Including data in the HTML file allows for viewing the map locally on some browsers (e.g. Chrome and Opera).

Anyway - I added a second note about this in the manual.
