### ISSUE TITLE
leafletR does not support Chinese character well(GBK)?

### ISSUE THREAD

**Issue by Ophelin777** [chgrl/leafletR#14]
As there are Chinese characters contained in popup, i don't know why they are showed as unrecognizable codes on the final html page. I have already change these characters into character string(originally factor).

This problem also appears when i use toGeoJSON function to get a .geojson file. All the Chinese characters are changed into number(such as 1 ,159 and so on )

Thank you~

**Comment by chgrl** [comment]
Hi! Could you please give more details. Chinese characters are generally supported.
I just tried:
```
library(leafletR)
data(quakes)
quakes$chinese <- rep("你好", 1000)
dat <- toGeoJSON(data=quakes, dest=tempdir())
map <- leaflet(data=dat, dest=tempdir(), popup="chinese")
map
```
And it works:
![leafchinese](https://cloud.githubusercontent.com/assets/6951018/5617170/0548dc44-950c-11e4-9eb8-34d11a6fbcee.png)

What type of data are you using? If you use an external spatial data files (shapefile etc.), the conversion over the Ogre-API used by leafletR (http://ogre.adc4gis.com) might be the problem. I did not test that yet.

Which platform are you using? I'm only able to test on OSX.

**Comment by chgrl** [comment]
Just tested Ogre with a shapefile - all fine, too.

**Comment by Ophelin777** [comment]
my computer system is Windows 7 (Language : Chinese). And i try the codes above and the result turns out to be the same.
But if i change the encoding of the data into utf-8  and run the code on Linux Mint 17.1(64-bit, language: zh_CN.UTF-8), then the chinese character can display correctly.

**Comment by Ophelin777** [comment]
![pic](https://cloud.githubusercontent.com/assets/7766422/6406581/a5722d1c-be6d-11e4-8f77-b7658247cac3.jpg)

**Comment by chgrl** [comment]
On my OSX machine the created geojson file is automatically utf-8 encoded. Trying to change the encoding into ISO latin or Windows latin fails due to "unmappable characters".
If I got you right, you tried the utf-8 encoded data on Linux and it worked. How's utf-8 working on the Windows machine?
I'm sorry, but I have no Windows machine for testing.

**Comment by chgrl** [comment]
Ok now?

**Comment by Ophelin777** [comment]
till cannot work under windows system, but  OSX and linux are OK
