### ISSUE TITLE
feature using basemap list as 'background' map no longer working?

### ISSUE THREAD

**Issue by rlzijdeman** [chgrl/leafletR#16]
Hi I seem to remember that I could create a basemap myself (e.g. based on a historical map) and overlay it on the mqsat map. 

I think this feature is described on p.6 of the CRAN leafletR documentation, but it no longer seems to work:

## example 1
map <- leaflet(base.map=list("osm", "mqsat", "tls"))
map

#### what I'm actually trying to do is to overlay a historic map of the Netherlands on the mqsat map of the world:
addBaseMap(
  name="nl1800", 
  title="nl1800", 
  url="http://maps.nypl.org/warper/maps/tile/7398/{z}/{x}/{y}.png",
  options=list(
    attribution='&copy; <a href="http://maps.nypl.org/warper/", target=
      "_blank">NYPL Map Warper</a>'
  )
)

map <- leaflet(base.map=list("nl1800", "mqsat"))
map

**Comment by chgrl** [comment]
Hi Richard,

the base maps are added to the map one after the other starting with the first in the list. So your historic Netherlands map is hidden behind the world map.

Try a reverse list:
```
map <- leaflet(base.map=list("mqsat","nl1800"))
map
```

**Comment by rlzijdeman** [comment]
cheers!
