### ISSUE TITLE
Integrate Leaflet.label plugin

### ISSUE THREAD

**Issue by onehundredpercenttexan** [chgrl/leafletR#17]
Feature request :)
It would be awesome to have labeling capabilities (static and hover) from this plugin!
   
https://github.com/Leaflet/Leaflet.label

Thanks for this great R package!

**Comment by chgrl** [comment]
Uh - when there's time... :-)

**Comment by onehundredpercenttexan** [comment]
That would be awesome! I tried to figure out how to incorporate the additional functionality within your brew files but soon realized that my lack of expertise in Javascript/HTML (Leaflet in particular) was going to present some pretty large hurdles. Thanks for bridging the gap for R programmers :+1:

**Comment by chgrl** [comment]
By the way, what do you want to do exactly? As leafletR is for visualizing your (R-) data, what shall the labels show - properties of the data, like a mouseover-popup? Or do you want to add extra markers/shapes with labels?

**Comment by onehundredpercenttexan** [comment]
Primarily, the former; I'd love to be able to choose either a static label or mouseover-popup and add that to an existing layer.

**Comment by tiernanmartin** [comment]
+1 for the ability to add extra markers/shapes with labels! 

It would be useful for adding static identification information to maps when the mouse-over popup is already dedicated to revealing other information. 

For example, I'm creating a map of census data which shows a choropleth at the tract level. I'm utilizing mouse-over popup to provide detailed information about each individual census tract. However, when the viewer is zoomed out it would be useful to clearly identify the different counties – that's where this static label feature would help me out.

Thanks for the great package!

**Comment by chgrl** [comment]
Hi @onehundredpercenttexan and @tiernanmartin,
I put some work into this and now you can use labels.

```
library(leafletR)
dat <- toGeoJSON(data=quakes[1:10,], dest=tempdir())
map <- leaflet(data=dat, dest=tempdir(), popup="stations", label="mag")
map
```

Unfortunately it does not work with lines and polygons. Seems to be a problem of the plugin. Mayby @jacobtoye can tell us, whether Leaflet.label works with GeoJSON-polygons loaded via query.

Christian

**Comment by chgrl** [comment]
I close this for now...
