### ISSUE TITLE
toGeoJSON create a big size file, is it ok?

### ISSUE THREAD

**Issue by wa2003** [chgrl/leafletR#24]
when I use
hp.dat<-toGeoJSON(data=hp_display[],lat.lon=c(6,5));
it create a big hp_display.geojson, it's about 800M.
why? is it wrong?
> str(hp_display)
Classes ‘tbl_df’ and 'data.frame':	3035 obs. of  6 variables:
 $ loupanmingcheng: chr  "COCO蜜城" "SOLO黄金岁月" "TAHA时区" "UHN国际村" ...
 $ fangchangeshu  : int  49 31 140 51 7 1 46 23 235 424 ...
 $ junjia         : num  0.894 0.754 0.85 5.175 0.936 ...
 $ city           : chr  "青岛" "青岛" "青岛" "北京" ...
 $ longitude      : num  120 120 120 116 117 ...
 $ latitude       : num  36.2 36.1 36.3 40 39.5 ...

**Comment by chgrl** [comment]
Fixed - toGeoJSON now supports dplyr:tbl_df objects.

Thanks.
