### ISSUE TITLE
Travis Builds

### ISSUE THREAD

**Issue by jhollist** [chgrl/leafletR#27]
Noticed you were having same issues with Travis and rgdal.  

The yml that now works for me is:

language: r
warnings_are_errors: true
env:
  global:
    - NOT_CRAN=true
before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

r_binary_packages:
  - rgdal

r_github_packages:
- jimhester/covr

after_success:
- Rscript -e 'library(covr); coveralls()'

The r_binary_packages does the trick!

**Comment by jhollist** [comment]
Ooops... bullets got rendered.  

This example is also at:  https://github.com/jhollist/quickmapr/blob/master/.travis.yml

**Comment by chgrl** [comment]
Thanks a lot.

**Comment by jhollist** [comment]
No prob.  Hope it helped.  I had been banging my head against it for a while.
