### ISSUE TITLE
Map Layer showing as grey

### ISSUE THREAD

**Issue by gmckinnon** [chgrl/leafletR#29]
Hi, When I run the example quakes code, the map opens up in a new browser and the legend, zoom buttoms and osm/open maps footer is showing but the whole map area is grey. 

 believe this is an issue with my office firewall etc as when I am off the network it works but I am wondering if there is any known way to tell leaflet to access my proxy.

thanks.

**Comment by chgrl** [comment]
Hi.
As the map is just a website, it's the browser that have to access the internet using the proxy, not R or leaflet. Sorry, but I have no idea about this.

Christian

**Comment by juliohm** [comment]
I am having the exact same issue. I don't know if it is related to proxies though, everything should work just fine.
