### ISSUE TITLE
Empty map with styleSingle 

### ISSUE THREAD

**Issue by adrientaudiere** [chgrl/leafletR#32]
Dear Christian Graul, 

First thank you for this very useful R package. 
I found recently a problem with the marker in styleSingle even using the last version of leafletR (0.4). Here is a minimal example code I found in your answer to an other issue. It is strange because my code run well two month ago and that the resulting html file (I built two month ago) show now the same problem. I tried also with version 0.33 without success. Thus I think it is more a problem with maki but my skills are not sufficient to go further. 

```r
# When using marker
library(leafletR)
data(quakes)
dat1 <- toGeoJSON(data=quakes[1:10,], name="Quakes 1", dest=tempdir())
dat2 <- toGeoJSON(data=quakes[11:20,], name="Quakes 2", dest=tempdir())

# simple colored markers
sty1 <- styleSingle(marker="green") # only color

# markers with label, color and size
sty2 <- styleSingle(marker=c("triangle", "#E41A1C", "s"))

map <- leaflet(data=list(dat1, dat2), dest=tempdir(), style=list(sty1, sty2))
map


# Without using marker
library(leafletR)
data(quakes)
dat1 <- toGeoJSON(data=quakes[1:10,], name="Quakes 1", dest=tempdir())
dat2 <- toGeoJSON(data=quakes[11:20,], name="Quakes 2", dest=tempdir())

# simple colored markers
sty1 <- styleSingle(col="green") # only color

# markers with label, color and size
sty2 <- styleSingle(fill="#E41A1C")

map <- leaflet(data=list(dat1, dat2), dest=tempdir(), style=list(sty1, sty2))
map
```

Thanks again for this package.

**Comment by chgrl** [comment]
Hi Adrien,

thanks for reporting this error. It seems that using the maki markers api now requires an access token. :-(
Maybe I have to use another marker-plugin.

Best
Christian

**Comment by chgrl** [comment]
Quick fix using a public token.
Try it out. :-)

Best Christian

**Comment by adrientaudiere** [comment]
It works perfect!
Thanks a lot.

Best,
Adrien
